#include <iostream>
#include <iomanip>

//------------------------------------------------------------------------------
#include "includes/histogram/histogram.h"



//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

void basic_test(bool debug=false);

int main(int argv, char** argc)
{
  cout << "\n" << endl;

  basic_test();

  cout << "\n\n=====================" << endl;
  return 0;
}

void basic_test(bool debug)
{
  srand(333);
  int rolls = 500;
  int testCounts[21] = {0};
  generateHistogramArray(testCounts, rolls);
  for (int i=0; i<21; i++) {
    cout << testCounts[i] << "=>";
  }
  cout << "|||" << endl;

  printHistogram(testCounts);
}

/*
NOT CMAKE PROJECT

folder structure:
histogram
├── includes
│   └── histogram
│       └── histogram.h
└── main.cpp


0=>0=>7=>8=>15=>16=>31=>43=>45=>56=>63=>59=>49=>39=>28=>19=>9=>6=>5=>2=>0=>|||
 4: 
 5: 
 6: XXXXXXX
 7: XXXXXXXX
 8: XXXXXXXXXXXXXXX
 9: XXXXXXXXXXXXXXXX
10: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
11: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
12: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
13: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
14: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
15: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
16: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
17: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
18: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
19: XXXXXXXXXXXXXXXXXXX
20: XXXXXXXXX
21: XXXXXX
22: XXXXX
23: XX
24: 


=====================
*/