#include "gtest/gtest.h"
#include <cmath>
#include <iostream>
#include <iomanip>
#include <set>
#include <vector>
#include <list>

//------------------------------------------------------------------------------
//Files we are testing:
#include "../../includes/node/node.h"
#include "../../includes/linked_list_functions/linked_list_functions.h"
#include "../../includes/list_iterated/list_iterated.h"
#include "../../includes/reverse_list/reverse_list.h"
//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

bool basic_test(bool debug = false)
{
  List<int> list;

  // insert items
  for (int i = 1; i < 10; i++)
  {
    list.insert_head(i);
  }
  cout << endl;
  cout << list;

  // 1. reverse entire linked list
  reverseList(list);
  cout << list;

  // 2. reverse first N nodes in linked list
  reverseN(list, 3);
  cout << list;

  // 3. reverse partial nodes of range [m, n] in linked list
  reverseBetween(list, 5, 8);
  cout << list;

  cout << "\n\n--------- D O N E ----------------" << endl << endl;
  return true;
}


//Lord help me! 
bool debug = false;

TEST(ITERATED_LIST, TestReverseList)
{
  bool success = basic_test(debug);
  EXPECT_EQ(success, true);
}

int main(int argc, char **argv)
{
  if (argc>1){
    debug = argv[1][0]=='t';
  }
  ::testing::InitGoogleTest(&argc, argv);
  std::cout<<"\n\n----------running basic_test.cpp---------\n\n"<<std::endl;
  return RUN_ALL_TESTS();
}


/*
build git:(master)  😊 $> tree ../includes 
../includes
├── linked_list_functions
│   └── linked_list_functions.h
├── list_iterated
│   └── list_iterated.h
├── node
│   └── node.h
└── reverse_list
    └── reverse_list.h
4 directories, 4 files

build git:(master)  😊 $> ./bin/basic_test
----------running basic_test.cpp---------


[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ITERATED_LIST
[ RUN      ] ITERATED_LIST.TestReverseList

[9]->[8]->[7]->[6]->[5]->[4]->[3]->[2]->[1]->|||
[1]->[2]->[3]->[4]->[5]->[6]->[7]->[8]->[9]->|||
[3]->[2]->[1]->[4]->[5]->[6]->[7]->[8]->[9]->|||
[3]->[2]->[1]->[4]->[8]->[7]->[6]->[5]->[9]->|||


--------- D O N E ----------------

[       OK ] ITERATED_LIST.TestReverseList (0 ms)
[----------] 1 test from ITERATED_LIST (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.
build git:(master)  😊 $> 
*/