#include <iostream>
#include <iomanip>

//------------------------------------------------------------------------------
#include "includes/roman_numeral/roman_numeral.h"



//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

void basic_test(bool debug=false);

int main()
{
  cout << "\n" << endl;

  basic_test();

  cout << "\n\n=====================" << endl;
  return 0;
}


void basic_test(bool debug)
{
  int n;
  string r;

  r = get_roman_numeral(1978);
  cout << "1978 in roman numeral is: " << r << endl << endl;

  n = roman_to_decimal("MDCCCLVII");
  cout << "MDCCCLVII is " << n << endl << endl;
}

/*
NOT CMAKE PROJECT

folder structure:
roman_numeral
├── includes
│   └── roman_numeral
│       └── roman_numeral.h
└── main.cpp

roman_numeral $> g++ main.cpp -o main && ./main

1978 in roman numeral is: MCMLXXVIII

MDCCCLVII is 1857



=====================
*/